export const Lib = {
    ADD_POST_ACTION: 'ADD_POST',
    INIT_MENU_ACTION: 'INIT_MENU',
    ADD_MAP_ACTION: 'ADD_MAP',
    ADD_MARKER_ACTION: 'ADD_MARKER',
    SET_SEARCH_PROPS_ACTION: 'SET_SEARCH_PROPS',
    SET_MAP_PROPS_ACTION: 'SET_MAP_PROPS',
    SET_MAP_MARKERS_ACTION: 'SET_MAP_MARKERS',
    SET_FILTER_TERMS_ACTION: 'SET_FILTER_TERMS',
    SET_USER_DATA_ACTION: 'SET_USER_DATA',
    SET_TESTIMONIAL_ACTIVE_ITEM_ACTION: 'SET_TESTIMONIAL_ACTIVE_ITEM',

    THEME_PREFIX: 'wp-property-pro-',
    STRING_ARRAY_DELIMITER: '-'
};