export const Lib = {
    ADD_POST_ACTION: 'ADD_POST',
    INIT_MENU_ACTION: 'INIT_MENU',
    ADD_MAP_ACTION: 'ADD_MAP',
    ADD_MARKER_ACTION: 'ADD_MARKER',
    TOGGLE_MODAL_ACTION: 'TOGGLE_MODAL',
    SET_SEARCH_PROPS_ACTION: 'SET_SEARCH_PROPS',
    SET_SEARCH_RESULTS_ACTION: 'SET_SEARCH_RESULTS',
    SET_MAP_MARKERS_ACTION: 'SET_MAP_MARKERS',
    SET_FILTER_TERMS_ACTION: 'SET_FILTER_TERMS',
    SET_USER_DATA_ACTION: 'SET_USER_DATA',
    SET_SEARCH_TYPE: 'SET_SEARCH_TYPE',
    SET_TESTIMONIAL_ACTIVE_ITEM_ACTION: 'SET_TESTIMONIAL_ACTIVE_ITEM',

    THEME_PREFIX: 'wp-property-pro-',
    STRING_ARRAY_DELIMITER: '-',
    URL_DELIMITER: '/',
    EXTENSION_DELIMITER: '.',
    PROPERTY_LISTING_IMAGE_SIZE: '400x230',
    PROPERTY_PER_PAGE: 18,
    MIN_SEARCH_KEY_LENGTH: 3,
    TOP_AGGREGATIONS_COUNT: 5,
    MOBILE_WIDTH: 768
};
